
# scripts/generate_ai_gemini.py
import os
import time
import random
import pandas as pd
from dotenv import load_dotenv

from google import genai
from google.genai import types

OUTPUT_FILE = "data/raw/ai2_data.csv"
N_SAMPLES = 3000
SAVE_EVERY = 20

CATEGORIES = ["cs.AI", "cs.LG", "cs.CL", "stat.ML"]
TOPICS = [
    "multi-agent systems",
    "knowledge representation",
    "automated reasoning",
    "reinforcement learning",
    "transformers for NLP",
    "graph neural networks",
    "causal inference",
    "privacy-preserving ML",
    "robust optimization",
    "computer vision for medical imaging",
]

# Farklı hesaplarda farklı modeller erişilebilir olabiliyor.
# O yüzden sırayla deniyoruz.
MODEL_CANDIDATES = [
    "gemini-2.0-flash",
    "gemini-1.5-flash",
    "gemini-1.5-flash-8b",
]

def build_prompt(category: str, topic: str) -> str:
    return (
        f"Write a scientific arXiv-style abstract (150-250 words) for category {category}. "
        f"Topic: {topic}. "
        "Include problem, method, and results. Formal academic tone. "
        "Do NOT mention that it is AI-generated. Do NOT write 'As an AI'. "
        "Output only the abstract text."
    )

def load_existing_rows() -> list[dict]:
    if not os.path.exists(OUTPUT_FILE):
        return []
    try:
        df = pd.read_csv(OUTPUT_FILE)
        # Sadece gereken kolonlar
        if "text" in df.columns and "label" in df.columns:
            df = df[["text", "label"]]
        return df.to_dict("records")
    except Exception:
        return []

def pick_working_model(client: genai.Client) -> str:
    test_prompt = "Write a 3-sentence scientific abstract about graph neural networks."
    last_err = None

    for m in MODEL_CANDIDATES:
        try:
            resp = client.models.generate_content(
                model=m,
                contents=test_prompt,
                config=types.GenerateContentConfig(
                    temperature=0.7,
                    max_output_tokens=120,
                ),
            )
            txt = (resp.text or "").strip()
            if len(txt) > 30:
                print(f"[OK] Kullanılacak model: {m}")
                return m
        except Exception as e:
            last_err = e
            print(f"[MODEL DENEME] {m} çalışmadı: {e}")

    raise RuntimeError(f"Hiçbir model çalışmadı. Son hata: {last_err}")

def main():
    load_dotenv()
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("API key bulunamadı. .env içine GEMINI_API_KEY=... ekleyin.")

    # Yeni SDK (stabil)
    client = genai.Client(api_key=api_key)

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    rows = load_existing_rows()
    start_idx = len(rows)

    print("Gemini API - AI Abstract Generator")
    print(f"Hedef: {N_SAMPLES} abstract")
    print(f"Başlangıç: {start_idx}")
    print(f"Çıkış dosyası: {OUTPUT_FILE}")

    model_name = pick_working_model(client)

    for i in range(start_idx, N_SAMPLES):
        category = random.choice(CATEGORIES)
        topic = random.choice(TOPICS)
        prompt = build_prompt(category, topic)

        for attempt in range(1, 6):
            try:
                resp = client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=0.9,
                        max_output_tokens=350,
                    ),
                )
                text = (resp.text or "").strip()

                # Basit kalite kontrolleri
                if len(text) < 200:
                    raise ValueError("Çok kısa çıktı geldi.")

                low = text.lower()
                if "as an ai" in low or "ai-generated" in low or "generated by ai" in low:
                    raise ValueError("AI izi tespit edildi.")

                rows.append({"text": text, "label": "ai"})

                if (i + 1) % SAVE_EVERY == 0:
                    pd.DataFrame(rows).to_csv(OUTPUT_FILE, index=False)
                    print(f"[{i+1}/{N_SAMPLES}] kaydedildi -> {OUTPUT_FILE}")

                break

            except Exception as e:
                wait = min(30, 2 * attempt)
                print(f"[HATA] {i+1}/{N_SAMPLES} deneme {attempt}/5: {e} | {wait}s bekle")
                time.sleep(wait)

        else:
            # 5 denemede de olmazsa durdurup hatayı net görelim
            raise RuntimeError(f"{i+1}. örnek 5 denemede üretilemedi.")

        time.sleep(0.2)

    pd.DataFrame(rows).to_csv(OUTPUT_FILE, index=False)
    print(f"[TAMAMLANDI] {len(rows)} kayıt -> {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
